Add env variable to modify vibration time
ubports/usensord pull request #2
Opened 2019-12-20 23:13 UTC by Flohack74

Some devices, like the Oneplus One, need a longer time to kickoff the vibration motor so that the user gets actually a good feedback. With this env variable introduced here usensord can extend the vibration time a bit.

2019-12-20 23:43 UTC, Flohack74 commented
...and please squash it rather than merging, I don't want my Go failures to be persisted forever ^^

2019-12-21 01:10 UTC, mariogrip requested changes
Just small nitpicks, but otherwise LTGM :+1:

2019-12-21 01:10 UTC, mariogrip commented on haptic/haptic.go
> +		vibrateScale uint32
Please make the space here constant with the code above.

2019-12-21 01:10 UTC, mariogrip commented on usensord.go
> +)
Please add spaces before `)` to match the others.

2019-12-22 04:17 UTC, mariogrip approved these changes
LGTM :+1:

2019-12-22 04:17 UTC, merged

2019-12-22 04:21 UTC, mariogrip commented
sorry for the merge, but i fixed it so its squashed now :D